# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Tapps' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Tapps
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'RCTImage'
  #  'CxxBridge', # Include this for RN >= 0.47
  #  'DevSupport', # Include this to enable In-App Devmenu if RN >= 0.43
  #  'RCTText',
  #  'RCTNetwork',
  #  'RCTWebSocket', # Needed for debugging
  #  'RCTAnimation', # Needed for FlatList and animations running on native UI thread
    # Add any other subspecs you want to use in your project
  ]
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  pod 'RNI18n', :path => '../node_modules/react-native-i18n'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'



  pod 'RNImageCropPicker', :path => '../node_modules/react-native-image-crop-picker'

  target 'TappsTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'Tapps-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Tapps-tvOS

    inherit! :search_paths
    # Pods for testing


end

pod 'BraintreeDropIn', '~> 6.0'
pod 'CardIO'
pod 'Braintree/Apple-Pay'
pod 'Braintree/PayPal'
pod 'BraintreeDropIn/UIKit'
pod 'Firebase/Core'
pod 'Firebase/Auth', '~> 5.15.0'
pod 'Firebase/Database', '~> 5.15.0'
pod 'Firebase/Firestore', '~> 5.15.0'
